// SDL3 TTF API wrapper
SDL3FUNCTION (TTF_Init, 0)
SDL3FUNCTION (TTF_Quit, 0)
SDL3FUNCTIONVAR (TTF_OpenFont, if)
SDL3FUNCTION (TTF_CloseFont, 1)
SDL3FUNCTION (TTF_CreateRendererTextEngine, 1)
SDL3FUNCTION (TTF_DestroyRendererTextEngine, 1)
SDL3FUNCTION (TTF_CreateText, 4)
SDL3FUNCTION (TTF_SetTextColor, 5)
SDL3FUNCTION (TTF_GetTextSize, 3)
SDL3FUNCTIONVAR (TTF_DrawRendererText, iff)
SDL3FUNCTION (TTF_RenderText_Blended, 4)