// UILIB API wrapper
// Function types
UIFUNCTION (uiInit, 1)
UIFUNCTION (uiUninit, 0)
UIFUNCTION (uiFreeInitError, 1)
UIFUNCTION (uiMain, 0)
UIFUNCTION (uiQuit, 0)
UIFUNCTION (uiFreeText, 1)
// Control
UIFUNCTION (uiControlDestroy, 1)
UIFUNCTION (uiControlToplevel, 1)
UIFUNCTION (uiControlVisible, 1)
UIFUNCTION (uiControlShow, 1)
UIFUNCTION (uiControlHide, 1)
UIFUNCTION (uiControlEnabled, 1)
UIFUNCTION (uiControlEnable, 1)
UIFUNCTION (uiControlDisable, 1)
// Window
UIFUNCTION (uiNewWindow, 4)
UIFUNCTION (uiWindowTitle, 1)
UIFUNCTION (uiWindowSetTitle, 2)
UIFUNCTION (uiWindowPosition, 3)
UIFUNCTION (uiWindowSetPosition, 3)
UIFUNCTION (uiWindowOnPositionChanged, 3)
UIFUNCTION (uiWindowContentSize, 3)
UIFUNCTION (uiWindowSetContentSize, 3)
UIFUNCTION (uiWindowFullscreen, 1)
UIFUNCTION (uiWindowSetFullscreen, 2)
UIFUNCTION (uiWindowOnContentSizeChanged, 3)
UIFUNCTION (uiWindowOnClosing, 3)
UIFUNCTION (uiWindowOnFocusChanged, 3)
UIFUNCTION (uiWindowFocused, 1)
UIFUNCTION (uiWindowBorderless, 1)
UIFUNCTION (uiWindowSetBorderless, 2)
UIFUNCTION (uiWindowSetChild, 2)
UIFUNCTION (uiWindowMargined, 1)
UIFUNCTION (uiWindowSetMargined, 2)
UIFUNCTION (uiWindowResizeable, 1)
UIFUNCTION (uiWindowSetResizeable, 2)
// Button
UIFUNCTION (uiNewButton, 1)
UIFUNCTION (uiButtonText, 1)
UIFUNCTION (uiButtonSetText, 2)
UIFUNCTION (uiButtonOnClicked, 3)
// Box
UIFUNCTION (uiNewVerticalBox, 0)
UIFUNCTION (uiNewHorizontalBox, 0)
UIFUNCTION (uiBoxAppend, 3)
UIFUNCTION (uiBoxNumChildren, 1)
UIFUNCTION (uiBoxDelete, 2)
UIFUNCTION (uiBoxPadded, 1)
UIFUNCTION (uiBoxSetPadded, 2)
// Checkbox
UIFUNCTION (uiNewCheckbox, 1)
UIFUNCTION (uiCheckboxText, 1)
UIFUNCTION (uiCheckboxSetText, 2)
UIFUNCTION (uiCheckboxOnToggled, 3)
UIFUNCTION (uiCheckboxChecked, 1)
UIFUNCTION (uiCheckboxSetChecked, 2)
// Entry
UIFUNCTION (uiNewEntry, 0)
UIFUNCTION (uiNewPasswordEntry, 0)
UIFUNCTION (uiNewSearchEntry, 0)
UIFUNCTION (uiEntryText, 1)
UIFUNCTION (uiEntrySetText, 2)
UIFUNCTION (uiEntryOnChanged, 3)
UIFUNCTION (uiEntryReadOnly, 1)
UIFUNCTION (uiEntrySetReadOnly, 2)
// Label
UIFUNCTION (uiNewLabel, 1)
UIFUNCTION (uiLabelText, 1)
UIFUNCTION (uiLabelSetText, 2)
// Tab
UIFUNCTION (uiNewTab, 0)
UIFUNCTION (uiTabAppend, 3)
UIFUNCTION (uiTabInsertAt, 4)
UIFUNCTION (uiTabDelete, 2)
UIFUNCTION (uiTabNumPages, 1)
UIFUNCTION (uiTabMargined, 2)
UIFUNCTION (uiTabSetMargined, 3)
// Group
UIFUNCTION (uiNewGroup, 0)
UIFUNCTION (uiGroupTitle, 1)
UIFUNCTION (uiGroupSetTitle, 2)
UIFUNCTION (uiGroupSetChild, 2)
UIFUNCTION (uiGroupMargined, 1)
UIFUNCTION (uiGroupSetMargined, 2)
// Spinbox
UIFUNCTION (uiNewSpinbox, 2)
UIFUNCTION (uiSpinboxValue, 1)
UIFUNCTION (uiSpinboxSetValue, 2)
UIFUNCTION (uiSpinboxOnChanged, 3)
// Slider
UIFUNCTION (uiNewSlider, 2)
UIFUNCTION (uiSliderValue, 1)
UIFUNCTION (uiSliderSetValue, 2)
UIFUNCTION (uiSliderHasToolTip, 1)
UIFUNCTION (uiSliderSetHasToolTip, 2)
UIFUNCTION (uiSliderOnChanged, 3)
UIFUNCTION (uiSliderOnReleased, 3)
UIFUNCTION (uiSliderSetRange, 3)
// ProgressBar
UIFUNCTION (uiNewProgressBar, 0)
UIFUNCTION (uiProgressBarValue, 1)
UIFUNCTION (uiProgressBarSetValue, 2) 
// Separator
UIFUNCTION (uiNewHorizontalSeparator, 0)
UIFUNCTION (uiNewVerticalSeparator, 0)
// Combobox
UIFUNCTION (uiNewCombobox, 0)
UIFUNCTION (uiComboboxAppend, 2)
UIFUNCTION (uiComboboxInsertAt, 3)
UIFUNCTION (uiComboboxDelete, 2)
UIFUNCTION (uiComboboxClear, 1)
UIFUNCTION (uiComboboxNumItems, 1)
UIFUNCTION (uiComboboxSelected, 1)
UIFUNCTION (uiComboboxSetSelected, 2)
UIFUNCTION (uiComboboxOnSelected, 3)
// EditableCombobox
UIFUNCTION (uiNewEditableCombobox, 0)
UIFUNCTION (uiEditableComboboxAppend, 2)
UIFUNCTION (uiEditableComboboxText, 1)
UIFUNCTION (uiEditableComboboxSetText, 2)
UIFUNCTION (uiEditableComboboxOnChanged, 3)
// RadioButtons
UIFUNCTION (uiNewRadioButtons, 0)
UIFUNCTION (uiRadioButtonsAppend, 2)
UIFUNCTION (uiRadioButtonsSelected, 1)
UIFUNCTION (uiRadioButtonsSetSelected, 2)
UIFUNCTION (uiRadioButtonsOnSelected, 3)
// DateTimePicker
UIFUNCTION (uiNewDateTimePicker, 0)
UIFUNCTION (uiNewDatePicker, 0)
UIFUNCTION (uiNewTimePicker, 0)
UIFUNCTION (uiDateTimePickerTime, 2)
UIFUNCTION (uiDateTimePickerSetTime, 2)
UIFUNCTION (uiDateTimePickerOnChanged, 3)
// MultilineEntry
UIFUNCTION (uiNewMultilineEntry, 0)
UIFUNCTION (uiNewNonWrappingMultilineEntry, 0)
UIFUNCTION (uiMultilineEntryText, 1)
UIFUNCTION (uiMultilineEntrySetText, 2)
UIFUNCTION (uiMultilineEntryAppend, 2)
UIFUNCTION (uiMultilineEntryOnChanged, 3)
UIFUNCTION (uiMultilineEntryReadOnly, 1)
UIFUNCTION (uiMultilineEntrySetReadOnly, 2)
// MenuItem
UIFUNCTION (uiMenuItemEnable, 1)
UIFUNCTION (uiMenuItemDisable, 1)
UIFUNCTION (uiMenuItemOnClicked, 3)
UIFUNCTION (uiMenuItemChecked, 1)
UIFUNCTION (uiMenuItemSetChecked, 2)
// Menu
UIFUNCTION (uiNewMenu, 1)
UIFUNCTION (uiMenuAppendItem, 2)
UIFUNCTION (uiMenuAppendCheckItem, 2)
UIFUNCTION (uiMenuAppendQuitItem, 1)
UIFUNCTION (uiMenuAppendPreferencesItem, 1)
UIFUNCTION (uiMenuAppendAboutItem, 1)
UIFUNCTION (uiMenuAppendSeparator, 1)
// Standard Dialogs
UIFUNCTION (uiOpenFile, 1)
UIFUNCTION (uiOpenFolder, 1)
UIFUNCTION (uiSaveFile, 1)
UIFUNCTION (uiMsgBox, 3)
UIFUNCTION (uiMsgBoxError, 3)
// Area
UIFUNCTION (uiNewArea, 1)
UIFUNCTION (uiNewScrollingArea, 3)
UIFUNCTION (uiAreaSetSize, 3)
UIFUNCTION (uiAreaQueueRedrawAll, 1)
UIFUNCTION (uiAreaScrollTo, 5)
// DrawPath
UIFUNCTION (uiDrawNewPath, 1)
UIFUNCTION (uiDrawFreePath, 1)
UIFUNCTION (uiDrawPathNewFigure, 3)
UIFUNCTION (uiDrawPathNewFigureWithArc, 7)
UIFUNCTION (uiDrawPathLineTo, 3)
UIFUNCTION (uiDrawPathArcTo, 7)
UIFUNCTION (uiDrawPathBezierTo, 7)
UIFUNCTION (uiDrawPathCloseFigure, 1)
UIFUNCTION (uiDrawPathAddRectangle, 5)
UIFUNCTION (uiDrawPathEnded, 1)
UIFUNCTION (uiDrawPathEnd, 1)
// Matrix
UIFUNCTION (uiDrawMatrixSetIdentity, 1)
UIFUNCTION (uiDrawMatrixTranslate, 3)
UIFUNCTION (uiDrawMatrixScale, 5)
UIFUNCTION (uiDrawMatrixRotate, 4)
UIFUNCTION (uiDrawMatrixSkew, 5)
UIFUNCTION (uiDrawMatrixMultiply, 2)
UIFUNCTION (uiDrawMatrixInvertible, 1)
UIFUNCTION (uiDrawMatrixInvert, 1)
UIFUNCTION (uiDrawMatrixTransformPoint, 3)
UIFUNCTION (uiDrawMatrixTransformSize, 3)
// DrawContext
UIFUNCTION (uiDrawSave, 1)
UIFUNCTION (uiDrawRestore, 1)
UIFUNCTION (uiDrawTransform, 2)
UIFUNCTION (uiDrawClip, 2)
UIFUNCTION (uiDrawStroke, 4)
UIFUNCTION (uiDrawFill, 3)
// ColorButton
UIFUNCTION (uiNewColorButton, 0)
UIFUNCTION (uiColorButtonColor, 5)
UIFUNCTION (uiColorButtonSetColor, 5)
UIFUNCTION (uiColorButtonOnChanged, 3)
// Form
UIFUNCTION (uiNewForm, 0)
UIFUNCTION (uiFormAppend, 4)
UIFUNCTION (uiFormNumChildren, 1)
UIFUNCTION (uiFormDelete, 2)
UIFUNCTION (uiFormPadded, 1)
UIFUNCTION (uiFormSetPadded, 2)
// Grid
UIFUNCTION (uiNewGrid, 0)
UIFUNCTION (uiGridAppend, 10)
UIFUNCTION (uiGridInsertAt, 10)
UIFUNCTION (uiGridPadded, 1)
UIFUNCTION (uiGridSetPadded, 2)
// Image
UIFUNCTION (uiNewImage, 2)
UIFUNCTION (uiFreeImage, 1)
UIFUNCTION (uiImageAppend, 5)
// TableValue
UIFUNCTION (uiTableValueGetType, 1)
UIFUNCTION (uiNewTableValueString, 1)
UIFUNCTION (uiTableValueString, 1)
UIFUNCTION (uiNewTableValueImage, 1)
UIFUNCTION (uiTableValueImage, 1)
UIFUNCTION (uiNewTableValueInt, 1)
UIFUNCTION (uiTableValueInt, 1)
UIFUNCTION (uiNewTableValueColor, 4)
UIFUNCTION (uiTableValueColor, 4)
// Table
UIFUNCTION (uiNewTable, 1)
UIFUNCTION (uiTableAppendTextColumn, 5)
UIFUNCTION (uiTableAppendImageColumn, 3)
UIFUNCTION (uiTableAppendImageTextColumn, 6)
UIFUNCTION (uiTableAppendCheckboxColumn, 4)
UIFUNCTION (uiTableAppendCheckboxTextColumn, 7)
UIFUNCTION (uiTableAppendProgressBarColumn, 3)
UIFUNCTION (uiTableAppendButtonColumn, 3)
UIFUNCTION (uiTableHeaderVisible, 1)
UIFUNCTION (uiTableHeaderSetVisible, 2)
UIFUNCTION (uiTableOnRowClicked, 3)
UIFUNCTION (uiTableOnRowDoubleClicked, 3)
UIFUNCTION (uiTableHeaderSetSortIndicator, 3)
UIFUNCTION (uiTableHeaderSortIndicator, 2)
UIFUNCTION (uiTableHeaderOnClicked, 3)
UIFUNCTION (uiTableColumnWidth, 2)
UIFUNCTION (uiTableColumnSetWidth, 3)
UIFUNCTION (uiTableGetSelectionMode, 1)
UIFUNCTION (uiTableSetSelectionMode, 2)
UIFUNCTION (uiTableOnSelectionChanged, 3)
UIFUNCTION (uiTableGetSelection, 1)
UIFUNCTION (uiTableSetSelection, 2)
UIFUNCTION (uiFreeTableSelection, 1)
